### ISSUE TITLE
Markdown for Text component

### ISSUE THREAD

**Issue by SuperBesse** [Expensify/react-native-live-markdown#193]
Thanks for this lib, it's a great job. 
In my project, i want to display markdow in a input and after as message.
Have you a lib to display markdow in a text and not only in a textinput ?

**Comment by tomekzaw** [comment]
@SuperBesse Thank you for your kind words as well as submitting this feature request.

Rendering Markdown-formatted text is also an important and very commom use case, that's why we are also working on `MarkdownText` component, see the draft PR here:
* https://github.com/Expensify/react-native-live-markdown/pull/125

**Comment by SuperBesse** [comment]
Thanks for the answer, i need to update RN and i will test your component.
